# Server configuration
server.port=${PORT:8080}

# Database configuration
spring.datasource.url=${DB_URL:jdbc:h2:mem:northpaydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA and Hibernate configuration
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary configuration placeholders
cloudinary.cloud-name=dqft7xrcq
cloudinary.api-key=144382121635355
cloudinary.api-secret=HOTYHi-iqN_mTuzCo2AybhMlK-Q

# Spring Mail configuration (Template for Gmail/SendGrid)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rodrigodaremberg@gmail.com
spring.mail.password=iybyzaejpmslgbdt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=*

# Client Application URL (For Onboarding Link activation)
app.client.url=http://localhost:4200
